eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
  instance:
    prefer-ip-address: true
spring:
  application:
    name: eruekaClientTwo
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config
  profiles:
    active: dev
server:
  port: 8003