#eureka是一个高可用的组件，它没有后端缓存，每一个实例注册之后需要向注册中心发送心跳（因此可以在内存中完成），在默认情况下erureka server也是一个eureka client ,
#必须要指定一个 server

eureka:
  #服务注册类配置
  client:
    #指定服务注册中心地址
    service-url:
      defaultZone: http://localhost:8761/eureka/
    #启动服务注册 默认 true
    register-with-eureka: false
    # 检索服务 默认 true
    fetch-registry: true
    # 从Eureka服务器端获取注册信息的间隔时间，单位：秒  默认30
    registry-fetch-interval-seconds: 30
    #连接 Eureka Server 的超时时间，单位：秒  默认 5
    eureka-server-connect-timeout-seconds: 20
    # 读取 Eureka Server 信息的超时时间，单位：秒 默认 8
    eureka-server-read-timeout-seconds: 20
    # 获取实例时是否过滤，只保留UP状态的实例 默认 true
    filter-only-up-instances: true
    #Eureka 服务端连接空闲关闭时间，单位：秒  默认30
    eureka-connection-idle-timeout-seconds: 50
    #从Eureka 客户端到所有Eureka服务端的连接总数 默认200
    eureka-server-total-connections: 200
    #从Eureka客户端到每个Eureka服务主机的连接总数 默认50
    eureka-server-total-connections-per-host: 50
  #服务注册中心配置
  server:
    #关闭注册中心的保护机制，Eureka 会统计15分钟之内心跳失败的比例低于85%将会触发保护机制，不剔除服务提供者，如果关闭服务注册中心将不可用的实例正确剔除
    #只在开发环境配置 （生产环境为true）
    enable-self-preservation: false
  #服务实例类配置
  instance:
    #不使用主机名来定义注册中心的地址，而使用IP地址的形式，如果设置了eureka.instance.ip-address 属性，则使用该属性配置的IP，否则自动获取除环路IP外的第一个IP地址
    prefer-ip-address: false
    #IP地址
    ip-address:
    #设置当前实例的主机名称
    hostname: localhost
    #服务名，默认取 spring.application.name 配置值，如果没有则为 unknow
    appname: instanceTest
    #定义服务续约任务（心跳）的调用间隔，单位：秒 默认30
    lease-renewal-interval-in-seconds: 30
    #定义服务失效的时间，单位：秒 默认90
    lease-expiration-duration-in-seconds: 90
    #状态页面的URL，相对路径，默认使用 HTTP 访问，如果需要使用 HTTPS则需要使用绝对路径配置   默认/info
    status-page-url-path: /info
    # 状态页面的URL，绝对路径
    #    status-page-url:
    #健康检查页面的URL，相对路径，默认使用 HTTP 访问，如果需要使用 HTTPS则需要使用绝对路径配置 默认/health
    health-check-url-path: /health
    #健康检查页面的URL，绝对路径
#    health-check-url:
spring:
  application:
    name: hostTest
server:
  port: 8761


